# Generated by Django 4.1.11 on 2023-10-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='yourmodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
