# Generated by Django 4.2.4 on 2024-01-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_yourmodel_description_alter_yourmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='members')),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
